name: fastlane tests

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup ruby & install fastlane
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Tuist generate
        uses: tuist/tuist-action@0.13.0
        with:
          command: 'fetch'

      - name: Tuist generate
        uses: tuist/tuist-action@0.13.0
        with:
          command: 'generate'

      - name: Run tests
        run: bundle exec fastlane ios tests
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}